comment: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

codecov:
  branch: develop
  ci:
    - !appveyor
    - !travis

fixes:
  - "/home/runner/work/afdko/::"
