# see https://pyup.io/docs/configuration/ for all available options

branch: develop
schedule: every week

requirements:
  - requirements.txt
    pin: False
  - requirements-dev.txt
    update: False
    pin: False
