/* Copyright 2014 Adobe Systems Incorporated (http://www.adobe.com/). All Rights Reserved.
   This software is licensed as OpenSource, under the Apache License, Version 2.0. This license is available at: http://opensource.org/licenses/Apache-2.0. *//***********************************************************************/

/*
 * ISOAdobe + Central European charset aggregate initializer. Element
 * values are glyph names. Comments are SIDs (where defined).
 */

/*   1 */ "space",
/*   2 */ "exclam",
/*   3 */ "quotedbl",
/*   4 */ "numbersign",
/*   5 */ "dollar",
/*   6 */ "percent",
/*   7 */ "ampersand",
/* 104 */ "quotesingle",
/*   9 */ "parenleft",
/*  10 */ "parenright",
/*  11 */ "asterisk",
/*  12 */ "plus",
/*  13 */ "comma",
/*  14 */ "hyphen",
/*  15 */ "period",
/*  16 */ "slash",
/*  17 */ "zero",
/*  18 */ "one",
/*  19 */ "two",
/*  20 */ "three",
/*  21 */ "four",
/*  22 */ "five",
/*  23 */ "six",
/*  24 */ "seven",
/*  25 */ "eight",
/*  26 */ "nine",
/*  27 */ "colon",
/*  28 */ "semicolon",
/*  29 */ "less",
/*  30 */ "equal",
/*  31 */ "greater",
/*  32 */ "question",
/*  33 */ "at",
/*  34 */ "A",
/*  35 */ "B",
/*  36 */ "C",
/*  37 */ "D",
/*  38 */ "E",
/*  39 */ "F",
/*  40 */ "G",
/*  41 */ "H",
/*  42 */ "I",
/*  43 */ "J",
/*  44 */ "K",
/*  45 */ "L",
/*  46 */ "M",
/*  47 */ "N",
/*  48 */ "O",
/*  49 */ "P",
/*  50 */ "Q",
/*  51 */ "R",
/*  52 */ "S",
/*  53 */ "T",
/*  54 */ "U",
/*  55 */ "V",
/*  56 */ "W",
/*  57 */ "X",
/*  58 */ "Y",
/*  59 */ "Z",
/*  60 */ "bracketleft",
/*  61 */ "backslash",
/*  62 */ "bracketright",
/*  63 */ "asciicircum",
/*  64 */ "underscore",
/* 124 */ "grave",
/*  66 */ "a",
/*  67 */ "b",
/*  68 */ "c",
/*  69 */ "d",
/*  70 */ "e",
/*  71 */ "f",
/*  72 */ "g",
/*  73 */ "h",
/*  74 */ "i",
/*  75 */ "j",
/*  76 */ "k",
/*  77 */ "l",
/*  78 */ "m",
/*  79 */ "n",
/*  80 */ "o",
/*  81 */ "p",
/*  82 */ "q",
/*  83 */ "r",
/*  84 */ "s",
/*  85 */ "t",
/*  86 */ "u",
/*  87 */ "v",
/*  88 */ "w",
/*  89 */ "x",
/*  90 */ "y",
/*  91 */ "z",
/*  92 */ "braceleft",
/*  93 */ "bar",
/*  94 */ "braceright",
/*  95 */ "asciitilde",
/* 173 */ "Adieresis",
/* 175 */ "Aring",
/* 177 */ "Ccedilla",
/* 178 */ "Eacute",
/* 186 */ "Ntilde",
/* 189 */ "Odieresis",
/* 195 */ "Udieresis",
/* 200 */ "aacute",
/* 203 */ "agrave",
/* 201 */ "acircumflex",
/* 202 */ "adieresis",
/* 205 */ "atilde",
/* 204 */ "aring",
/* 206 */ "ccedilla",
/* 207 */ "eacute",
/* 210 */ "egrave",
/* 208 */ "ecircumflex",
/* 209 */ "edieresis",
/* 211 */ "iacute",
/* 214 */ "igrave",
/* 212 */ "icircumflex",
/* 213 */ "idieresis",
/* 215 */ "ntilde",
/* 216 */ "oacute",
/* 219 */ "ograve",
/* 217 */ "ocircumflex",
/* 218 */ "odieresis",
/* 220 */ "otilde",
/* 222 */ "uacute",
/* 225 */ "ugrave",
/* 223 */ "ucircumflex",
/* 224 */ "udieresis",
/* 112 */ "dagger",
/* 161 */ "degree",
/*  97 */ "cent",
/*  98 */ "sterling",
/* 102 */ "section",
/* 116 */ "bullet",
/* 115 */ "paragraph",
/* 149 */ "germandbls",
/* 165 */ "registered",
/* 170 */ "copyright",
/* 153 */ "trademark",
/* 125 */ "acute",
/* 131 */ "dieresis",
"notequal",
/* 138 */ "AE",
/* 141 */ "Oslash",
/* 156 */ "plusminus",
"lessequal",
"greaterequal",
/* 100 */ "yen",
/* 152 */ "mu",
"partialdiff",
"summation",
/* 139 */ "ordfeminine",
/* 143 */ "ordmasculine",
/* 144 */ "ae",
/* 147 */ "oslash",
/* 123 */ "questiondown",
/*  96 */ "exclamdown",
/* 151 */ "logicalnot",
"radical",
/* 101 */ "florin",
"Delta",
/* 106 */ "guillemotleft",
/* 120 */ "guillemotright",
/* 121 */ "ellipsis",
/* 174 */ "Agrave",
/* 176 */ "Atilde",
/* 191 */ "Otilde",
/* 142 */ "OE",
/* 148 */ "oe",
/* 111 */ "endash",
/* 137 */ "emdash",
/* 105 */ "quotedblleft",
/* 119 */ "quotedblright",
/*  65 */ "quoteleft",
/*   8 */ "quoteright",
/* 159 */ "divide",
"lozenge",
/* 227 */ "ydieresis",
/* 198 */ "Ydieresis",
/*  99 */ "fraction",
/* 103 */ "currency",
/* 107 */ "guilsinglleft",
/* 108 */ "guilsinglright",
/* 109 */ "fi",
/* 110 */ "fl",
/* 113 */ "daggerdbl",
/* 117 */ "quotesinglbase",
/* 118 */ "quotedblbase",
/* 122 */ "perthousand",
/* 172 */ "Acircumflex",
/* 179 */ "Ecircumflex",
/* 171 */ "Aacute",
/* 180 */ "Edieresis",
/* 181 */ "Egrave",
/* 182 */ "Iacute",
/* 183 */ "Icircumflex",
/* 184 */ "Idieresis",
/* 185 */ "Igrave",
/* 187 */ "Oacute",
/* 188 */ "Ocircumflex",
/* 190 */ "Ograve",
/* 193 */ "Uacute",
/* 194 */ "Ucircumflex",
/* 196 */ "Ugrave",
/* 145 */ "dotlessi",
/* 126 */ "circumflex",
/* 127 */ "tilde",
/* 128 */ "macron",
/* 129 */ "breve",
/* 130 */ "dotaccent",
/* 132 */ "ring",
/* 133 */ "cedilla",
/* 134 */ "hungarumlaut",
/* 135 */ "ogonek",
/* 136 */ "caron",
/* 140 */ "Lslash",
/* 146 */ "lslash",
/* 192 */ "Scaron",
/* 221 */ "scaron",
/* 199 */ "Zcaron",
/* 228 */ "zcaron",
/* 160 */ "brokenbar",
/* 154 */ "Eth",
/* 167 */ "eth",
/* 197 */ "Yacute",
/* 226 */ "yacute",
/* 157 */ "Thorn",
/* 162 */ "thorn",
/* 166 */ "minus",
/* 168 */ "multiply",
/* 150 */ "onesuperior",
/* 164 */ "twosuperior",
/* 169 */ "threesuperior",
/* 155 */ "onehalf",
/* 158 */ "onequarter",
/* 163 */ "threequarters",
"Gbreve",
"gbreve",
"Idotaccent",
"Scedilla",
"scedilla",
"Cacute",
"cacute",
"Ccaron",
"ccaron",
"dcroat",
"Amacron",
"amacron",
"Abreve",
"abreve",
"Aogonek",
"aogonek",
"Dcaron",
"dcaron",
"Dcroat",
"Emacron",
"emacron",
"Edotaccent",
"edotaccent",
"Eogonek",
"eogonek",
"Ecaron",
"ecaron",
"Gcommaaccent",
"gcommaaccent",
"Imacron",
"imacron",
"Iogonek",
"iogonek",
"Kcommaaccent",
"kcommaaccent",
"Lacute",
"lacute",
"Lcommaaccent",
"lcommaaccent",
"Lcaron",
"lcaron",
"Nacute",
"nacute",
"Ncommaaccent",
"ncommaaccent",
"Ncaron",
"ncaron",
"Omacron",
"omacron",
"Ohungarumlaut",
"ohungarumlaut",
"Racute",
"racute",
"Rcommaaccent",
"rcommaaccent",
"Rcaron",
"rcaron",
"Sacute",
"sacute",
"Tcommaaccent",
"tcommaaccent",
"Tcaron",
"tcaron",
"Umacron",
"umacron",
"Uring",
"uring",
"Uhungarumlaut",
"uhungarumlaut",
"Uogonek",
"uogonek",
"Zacute",
"zacute",
"Zdotaccent",
"zdotaccent",
/* 114 */ "periodcentered",
"Scommaaccent",
"scommaaccent",
"commaaccent",
"Euro",