"UFO mode converts an abstract font to a UFO 2 font.\n",

"Note that it is NOT a full UFO writer. It writes only\n",
"the information from the Postscript font data. If the source\n",
"is an OTF or TTF font, it will NOT copy any of the meta data\n",
"from outside the font program table. Also, if the destination\n",
"is an already existing UFO font, tx will fail.\n",
"\n",
"When reading from a UFO font, tx will prefer GLIF files in the\n",
"layer 'com.adobe.type.processedglyphs'. You can select another\n",
"layer with the option '-altLayer <layer name>'. Use 'None' for\n",
"the layer name in order to have tx ignore the preferred layer\n",
"and read GLIF files from the foreground layer.\n",
