# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.9.4.dev67+g0fda11a1.d20230324'
__version_tuple__ = version_tuple = (3, 9, 4, 'dev67', 'g0fda11a1.d20230324')
