version: 2

jobs:
  linux-python3:
    docker:
      - image: circleci/python:3.7
    environment:
      XFLAGS: --coverage
      PYTHON: python
      PIP: pip
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Setup Python virtual environment"
          command: bash .circleci/setup_linux_pyenv.sh
      - run:
          name: "Run static code analysis (if it's not a tagged commit)"
          command: |
            if [[ -z $CIRCLE_TAG ]]; then
              bash .circleci/check_source_code.sh
            fi
      - run:
          name: "Build wheel, run tests, report coverage, and uninstall"
          command: |
            source venv/bin/activate
            $PYTHON setup.py bdist_wheel
            $PIP install dist/*.whl
            $PYTHON -m pytest --cov
            codecov
            $PIP uninstall --yes afdko
      # - store_artifacts:
      #     path: wheelhouse/

  osx-python3:
    macos:
      xcode: "10.3.0"
    environment:
      PYTHON: python3
      PIP: pip3
    steps:
      - checkout
      - run:
          name: "Setup Python virtual environment"
          command: bash .circleci/setup_mac_pyenv.sh
      - run:
          name: "Build wheel, run tests, and uninstall"
          command: |
            source venv/bin/activate
            $PIP wheel . --no-deps -w dist
            $PIP install dist/*.whl
            $PYTHON -m pytest
            $PIP uninstall --yes afdko
      # - store_artifacts:
      #     path: wheelhouse/

workflows:
  version: 2
  all-tests:
    jobs:
      - linux-python3:
          filters:  # run job for all branches and all tags
            tags:
              only: /.*/
      - osx-python3:
          filters:
            tags:
              only: /.*/
