#! /usr/bin/env bash
targetScript=makeInstancesUFO.py

cmdDirPath=`dirname $0`
cmdName=`basename $0`
if [ $cmdDirPath ] ; then
  cmdPath=$cmdDirPath
else
    cmdPath=`which $selfName`
    if [ ! $cmdPath ] ; then
        echo "Failed to derive parent directory for this command $0"
    fi
	cmdDirPath=`dirname $cmdPath`
fi

source "${cmdPath}/setFDKPaths"

$AFDKO_Python "${AFDKO_Scripts}/${targetScript}" "$@"
