/* Copyright 2014 Adobe Systems Incorporated (http://www.adobe.com/). All Rights Reserved.
   This software is licensed as OpenSource, under the Apache License, Version 2.0. This license is available at: http://opensource.org/licenses/Apache-2.0. *//***********************************************************************/

/*
 * DO NOT EDIT; this file is generated by the Perl script ucblock.pl.
 *
 * Unicode block information (struct type: UnicodeBlock). Ordered by first UV
 * in range. Ranges do not overlap. Bit for Supplementary UVs handled
 * separately
 */

{
	0x0020, 0x007E,    95, 0,  0, 0, "Basic Latin"
},
{
	0x0080, 0x00FF,   128, 0,  1, 0, "Latin-1 Supplement"
},
{
	0x0100, 0x017F,   128, 0,  2, 0, "Latin Extended-A"
},
{
	0x0180, 0x024F,   208, 0,  3, 0, "Latin Extended-B"
},
{
	0x0250, 0x02AF,    96, 0,  4, 0, "IPA Extensions"
},
{
	0x02B0, 0x02FF,    80, 0,  5, 0, "Spacing Modifier Letters"
},
{
	0x0300, 0x036F,   112, 0,  6, 0, "Combining Diacritical Marks"
},
{
	0x0370, 0x03FF,   144, 0,  7, 0, "Greek"
},
{
	0x0400, 0x04FF,   256, 0,  9, 0, "Cyrillic"
},
{
	0x0530, 0x058F,    96, 0, 10, 0, "Armenian"
},
{
	0x0590, 0x05FF,   112, 0, 11, 0, "Hebrew"
},
{
	0x0600, 0x06FF,   256, 0, 13, 0, "Arabic"
},
{
	0x0900, 0x097F,   128, 0, 15, 0, "Devanagari"
},
{
	0x0980, 0x09FF,   128, 0, 16, 0, "Bengali"
},
{
	0x0A00, 0x0A7F,   128, 0, 17, 0, "Gurmukhi"
},
{
	0x0A80, 0x0AFF,   128, 0, 18, 0, "Gujarati"
},
{
	0x0B00, 0x0B7F,   128, 0, 19, 0, "Oriya"
},
{
	0x0B80, 0x0BFF,   128, 0, 20, 0, "Tamil"
},
{
	0x0C00, 0x0C7F,   128, 0, 21, 0, "Telugu"
},
{
	0x0C80, 0x0CFF,   128, 0, 22, 0, "Kannada"
},
{
	0x0D00, 0x0D7F,   128, 0, 23, 0, "Malayalam"
},
{
	0x0E00, 0x0E7F,   128, 0, 24, 0, "Thai"
},
{
	0x0E80, 0x0EFF,   128, 0, 25, 0, "Lao"
},
{
	0x10A0, 0x10FF,    96, 0, 26, 0, "Georgian"
},
{
	0x1100, 0x11FF,   256, 0, 28, 0, "Hangul Jamo"
},
{
	0x1E00, 0x1EFF,   256, 0, 29, 0, "Latin Extended Additional"
},
{
	0x1F00, 0x1FFF,   256, 0, 30, 0, "Greek Extended"
},
{
	0x2000, 0x206F,   112, 0, 31, 0, "General Punctuation"
},
{
	0x2070, 0x209F,    48, 0, 32, 0, "Superscripts and Subscripts"
},
{
	0x20A0, 0x20CF,    48, 0, 33, 0, "Currency Symbols"
},
{
	0x20D0, 0x20FF,    48, 0, 34, 0, "Combining Marks for Symbols"
},
{
	0x2100, 0x214F,    80, 0, 35, 0, "Letterlike Symbols"
},
{
	0x2150, 0x218F,    64, 0, 36, 0, "Number Forms"
},
{
	0x2190, 0x21FF,   112, 0, 37, 0, "Arrows"
},
{
	0x2200, 0x22FF,   256, 0, 38, 0, "Mathematical Operators"
},
{
	0x2300, 0x23FF,   256, 0, 39, 0, "Miscellaneous Technical"
},
{
	0x2400, 0x243F,    64, 0, 40, 0, "Control Pictures"
},
{
	0x2440, 0x245F,    32, 0, 41, 0, "Optical Character Recognition"
},
{
	0x2460, 0x24FF,   160, 0, 42, 0, "Enclosed Alphanumerics"
},
{
	0x2500, 0x257F,   128, 0, 43, 0, "Box Drawing"
},
{
	0x2580, 0x259F,    32, 0, 44, 0, "Block Elements"
},
{
	0x25A0, 0x25FF,    96, 0, 45, 0, "Geometric Shapes"
},
{
	0x2600, 0x26FF,   256, 0, 46, 0, "Miscellaneous Symbols"
},
{
	0x2700, 0x27BF,   192, 0, 47, 0, "Dingbats"
},
{
	0x3000, 0x303F,    64, 0, 48, 0, "CJK Symbols and Punctuation"
},
{
	0x3040, 0x309F,    96, 0, 49, 0, "Hiragana"
},
{
	0x30A0, 0x30FF,    96, 0, 50, 0, "Katakana"
},
{
	0x3100, 0x312F,    48, 0, 51, 0, "Bopomofo"
},
{
	0x3130, 0x318F,    96, 0, 52, 0, "Hangul Compatibility Jamo"
},
{
	0x3200, 0x32FF,   150, 0, 54, 0, "Enclosed CJK Letters and Months"
},
{
	0x3300, 0x33FF,   150, 0, 55, 0, "CJK Compatibility"
},
{
	0x4E00, 0x9FFF, 16000, 0, 59, 0, "CJK Unified Ideographs"
},
{
	0xAC00, 0xD7A3,  5000, 0, 56, 0, "Hangul Syllables"
},
{
	0xE000, 0xF8FF,  6400, 0, 60, 0, "Private Use"
},
{
	0xF900, 0xFAFF,    150, 0, 61, 0, "CJK Compatibility Ideographs"
},
{
	0xFB00, 0xFB4F,    40, 0, 62, 0, "Alphabetic Presentation Forms"
},
{
	0xFB50, 0xFDFF,   688, 0, 63, 0, "Arabic Presentation Forms-A"
},
{
	0xFE20, 0xFE2F,    16, 0, 64, 0, "Combining Half Marks"
},
{
	0xFE30, 0xFE4F,    32, 0, 65, 0, "CJK Compatibility Forms"
},
{
	0xFE50, 0xFE6F,    32, 0, 66, 0, "Small Form Variants"
},
{
	0xFE70, 0xFEFF,   144, 0, 67, 0, "Arabic Presentation Forms-B"
},
{
	0xFF00, 0xFFEF,   150, 0, 68, 0, "Halfwidth and Fullwidth Forms"
},
{
	0xFFF0, 0xFFFF,    16, 0, 69, 0, "Specials"
},
/*
    {0x10000, 0x1007F, 1, 0, 0, 0, "Linear B Syllabary"},
    {0x10080, 0x100FF, 1, 0, 0, 0, "Linear B Ideograms"},
    {0x10100, 0x1013F, 1, 0, 0, 0, "Aegean Numbers"},
    {0x10140, 0x1018F, 1, 0, 0, 0, "Ancient Greek Numbers"},
 */
{
	0x10300, 0x1032F, 1, 0, 85, 0, "Old Italic"
},
{
	0x10330, 0x1034F, 1, 0, 86, 0, "Gothic"
},
/*
    {0x10380, 0x1039F, 1, 0, 0, 0, "Ugaritic"},
    {0x103A0, 0x103DF, 1, 0, 0, 0, "Old Persian"},
 */
{
	0x10400, 0x1044F, 1, 0, 87, 0, "Deseret"
},
/*
    {0x10450, 0x1047F, 1, 0, 0, 0, "Shavian"},
    {0x10480, 0x104AF, 1, 0, 0, 0, "Osmanya"},
    {0x10800, 0x1083F, 1, 0, 0, 0, "Cypriot Syllabary"},
    {0x10900, 0x1091F, 1, 0, 0, 0, "Phoenician"},
    {0x10A00, 0x10A5F, 1, 0, 0, 0, "Kharoshthi"},
    {0x12000, 0x123FF, 1, 0, 0, 0, "Cuneiform"},
    {0x12400, 0x1247F, 1, 0, 0, 0, "Cuneiform Numbers and Punctuation"},
 */
{
	0x1D000, 0x1D1FF, 1, 0, 88, 0, "Byzantine Musical Symbols and Musical Symbols"
},
/*	{0x1D100, 0x1D1FF, 1, 0, 0, 0, "Musical Symbols"},*/
/*
    {0x1D200, 0x1D24F, 1, 0, 0, 0, "Ancient Greek Musical Notation"},
    {0x1D300, 0x1D35F, 1, 0, 0, 0, "Tai Xuan Jing Symbols"},
    {0x1D360, 0x1D37F, 1, 0, 0, 0, "Counting Rod Numerals"},
 */
{
	0x1D400, 0x1D7FF, 1, 0, 89, 0, "Mathematical Alphanumeric Symbols"
},
/*
    {0x1FF80, 0x1FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x20000, 0x2A6D6, 1, 0, 0, 0, "CJK Unified Ideographs Extension B"},
    {0x2F800, 0x2FA1F, 1, 0, 0, 0, "CJK Compatibility Ideographs Supplement"},
    {0x2FF80, 0x2FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x3FF80, 0x3FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x4FF80, 0x4FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x5FF80, 0x5FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x6FF80, 0x6FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x7FF80, 0x7FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x8FF80, 0x8FFFF, 1, 0, 0, 0, "Unassigned"},
    {0x9FF80, 0x9FFFF, 1, 0, 0, 0, "Unassigned"},
 */
{
	0xFFF80, 0xFFFFF, 1, 0, 90, 0, "Supplementary Private Use Area-A"
},
{
	0x10FF80, 0x10FFFF, 1, 0, 91, 0, "Supplementary Private Use Area-B"
},
