table head {
  FontRevision 2.004;
} head;

table name {
  nameid 0 "\00A9 2014-2021 Adobe (http://www.adobe.com/).";
  nameid 7 "Noto is a trademark of Google Inc.";
  nameid 8 "Adobe";
  nameid 9 "Ryoko NISHIZUKA \897F\585A\6DBC\5B50 (kana, bopomofo & ideographs); Paul D. Hunt (Latin, Greek & Cyrillic); Sandoll Communications \C0B0\B3CC\CEE4\BBA4\B2C8\CF00\C774\C158, Soo-young JANG \C7A5\C218\C601 & Joo-yeon KANG \AC15\C8FC\C5F0 (hangul elements, letters & syllables)";
  nameid 10 "Dr. Ken Lunde (project architect, glyph set definition & overall production); Masataka HATTORI \670D\90E8\6B63\8CB4 (production & ideograph elements)";
  nameid 11 "http://www.google.com/get/noto/";
  nameid 12 "http://www.adobe.com/type/";
  nameid 13 "This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on an \0022AS IS\0022 BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language, permissions and limitations governing your use of this Font Software.";
  nameid 14 "http://scripts.sil.org/OFL";
} name;

table OS/2 {
  TypoAscender 880;
  TypoDescender -120;
  TypoLineGap 0;
  XHeight 543;
  CapHeight 733;
  WeightClass 400;
  WidthClass 5;
  Panose 2 11 5 0 0 0 0 0 0 0;
  FSType 0;
  Vendor "GOOG";
  winAscent 1160;
  winDescent 288;
} OS/2;

include(STAT.HW.fea);
